# Alert rules for PDF Splitter API

groups:
  - name: pdf_splitter_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # API down
      - alert: APIDown
        expr: up{job="pdf-splitter-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PDF Splitter API is down"
          description: "API instance {{ $labels.instance }} has been down for more than 1 minute"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      # Disk space low
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanizePercentage }} disk space remaining on {{ $labels.instance }}"

      # Too many active requests
      - alert: TooManyActiveRequests
        expr: http_requests_active > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many active requests"
          description: "{{ $value }} active requests on {{ $labels.instance }}"

      # PDF processing failures
      - alert: PDFProcessingFailures
        expr: rate(pdf_processing_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High PDF processing failure rate"
          description: "PDF processing failure rate is {{ $value }} per second"

      # WebSocket connection issues
      - alert: WebSocketConnectionIssues
        expr: rate(websocket_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "WebSocket connection issues"
          description: "WebSocket error rate is {{ $value }} per second"
