apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-splitter-data-pvc
  namespace: pdf-splitter
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
